### ISSUE TITLE
API should allow downloading of images without an annotation file

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#107]
For example the raw folder in https://viame.kitware.com/#/folder/5eb374f38d01d968cc1667f8 has images but no metadata/annotations by design, but you should still be able to download it.

**Comment by subdavis** [comment]
Related to #79

**Comment by subdavis** [comment]
## Plan

* For folders that are flagged with VIAME special meta (the ones you can annotate), Download will open a dialog with the option to download 1) media 2) annotations 3) annotations with historical data  (auxillary folder) 4) everything.
* For other folders, download will just send you a zip of the whole thing, like a regular girder directory download.

I'm going to add the "Export" option to the annotaiton view as well.   The toolbar is going to get crowded soon, so we need to rethink that.   We may want to reconsider the density of that toolbar.

**Comment by subdavis** [comment]
![Screenshot from 2020-05-15 14-31-43](https://user-images.githubusercontent.com/4214172/82345705-91158300-99c3-11ea-8859-35250f544126.png)
