### ISSUE TITLE
Fix browser-version-dependent bugs doing annotation editing

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#109]
I typically see one of two issues happening:

(1) When I right click a detection box it goes into edit mode successfully for that box, then when I left click another (separate) box it deletes the 2nd box (the latter). I haven't been able to reproduce this consistently yet but I've seen it happen in 3 instances. As soon as it happens it goes back to normal after it.

(2) In an older version of chrome when you right click a box to edit it the box becomes blue but it doesn't have the circles on box corners to enable resizing the box, but it doesn't switch into edit mode. You can then (while in the edit mode) draw a new box. The detection then has 2 boxes associated with it, see attached

<img width="1280" alt="two_detections_in_one" src="https://user-images.githubusercontent.com/2353972/81594915-a1a87680-938f-11ea-8f2a-51eef6218027.png">
.

**Comment by mattdawkins** [comment]
I think I have the 2nd one reproducable, go to https://viame.kitware.com/#/viewer/5eb372788d01d968cc165ced

left click big scallop, left click flounder, right click big scallop (bug appears, it doesn't go into edit mode but lets you draw a 2nd box)

**Comment by BryonLewis** [comment]
This may be fixed in my latest Draft PR.  I'll confirm the issue and see if it exists in my draft PR.

**Comment by BryonLewis** [comment]
Think I got it for the reproducible one, `editTrackId.value` of `0` is non-truthy so it failed some checks in the code.  I think it should be fixed in my latest PR.  Issue 1 and 2 should be fixed in my latest PR.
