### ISSUE TITLE
Controls are undocumented (Create modals within the APP)

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME-Web#11]
Most of the controls are undocumented.  I found out, for example, that you have to press "escape" in order to save the state of a track, otherwise if you adjust a track then move to the next frame, the adjustment is lost.

**Comment by subdavis** [comment]
You can also right click outside the box.

**Comment by BryonLewis** [comment]
Is the intention of this issue to provide some easy user direction for what to do in the annotations?  Like a brief description of mouse/keyboard controls and how to start or is more of a generic modal template that is needed?

**Comment by subdavis** [comment]
@BryonLewis I was thinking of having something simple like https://github.com/VIAME/VIAME-Web/wiki/User-Documentation#controls as a table in a dialog within the app.

Maybe it makes sense to replace the current button with a dialog that shows that table and a link at the bottom to open "Full user documentation"?

**Comment by BryonLewis** [comment]
@subdavis  Thanks, I was referencing that control table.  I didn't know how fancy we wanted to get with the help.  Like if we wanted state sensitive help that listed controls/information for the current state, but I'm probably look too far forward.

**Comment by BryonLewis** [comment]
Quick preview of what it would like.
![image](https://user-images.githubusercontent.com/61746913/79866240-73e09b00-83aa-11ea-9108-d8b9d50c28bc.png)

**Comment by subdavis** [comment]
Looks awesome!!
