### ISSUE TITLE
Have issue with one example video being uploaded but not all videos

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#110]
Out of the videos in vnas: other/projects/noaa, the .MP4 and .mpg videos seem fine though not the .mp4, don't know if issue with a particular codec, the video, or other

**Comment by subdavis** [comment]
Pretty simple bug:

1. the `mp4` you used is MPEG-4, not h264, so it wouldn't play.
2. transcoding should have handled this, except that the wrong video (the original, not the transcoded one, is being returned from the server.

@AlmightyYakob left a TODO

```
        # TODO: Instead of doing this lengthy operation, we should
        # set <videoItem>["meta"]["video"] = folder["_id"] on upload,
        # so it can be easily queried with Item().find({"video": folder["_id"]})
```

I'm going to do a variation of this, tagging the video with the proper encoding so it can be returned later.
