### ISSUE TITLE
Run pipelines dialogue should have different dropdowns for different types

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#111]
It's going to get crowded fairly fast, maybe have 3 sub dialogues, detectors, trackers, trained pipelines? I'm sure there's other ways to partition them.

At a minimum they should be listed in alphabetical order as a short-term solution

**Comment by subdavis** [comment]
![Screenshot from 2020-05-18 11-22-52](https://user-images.githubusercontent.com/4214172/82345598-73481e00-99c3-11ea-93a4-0514859c67d6.png)
