### ISSUE TITLE
Add optional track interpolation and associated setting to enable and disable it

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#120]
Enabling and disabling it during track creation is important (ideally on the top bar) because fish may be occluded or go out of frame for a number of frames before re-appearing

**Comment by aashish24** [comment]
based on our discussion, this feature may require reworking on data structures for tracks and detection. We could probably learn some lessons from the desktop UI fyi @BryonLewis @subdavis @AlmightyYakob

**Comment by subdavis** [comment]
This feature will probably require some discussion about how users will use this.

* Could a user want interpolated AND non-interpolated tracks in the same video?  Why would they want that?
* Could a user want to change the interpolation status of a track after creation?  Why would they want that?
* Is toggling interpolation really the best way to signal occlusion? Other apps I've seen keep interpolation on and add a boolean detection attribute "occluded" that can be turned on and off.

Also, the UI/UX for creating interpolated frames will likely be very different from creating keyframe-only tracks.   Good UI for such a workflow has been outlined pretty extensively in [vatic](http://www.cs.columbia.edu/~vondrick/vatic/ijcv.pdf) and [cvat](https://github.com/opencv/cvat).

It's probably a good idea here to engage more directly with the design team.  We could also engage with our in-house annotation team.  I've done this before, getting their feedback on annotation tooling has historically been really beneficial.

Technical note: an interpolation-capable GeoJS annotation app already exists in Janitor and Refiner.  Worth seeing how we can learn from those.
