### ISSUE TITLE
Species density plot is below axis on latest version

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#128]
![bar_shift](https://user-images.githubusercontent.com/2353972/82475674-d8227780-9a9a-11ea-9e86-30d4ce833561.png)

**Comment by BryonLewis** [comment]
Wasn't any change by us I believe but how it was originally.  I'll look into fixing it.  The axis is at the bottom of the graph, and the brighter white line is actually the mark for '10'.  It looks like for some reason the frame number for the x-axis is placed on the detection graph.

**Comment by BryonLewis** [comment]
JRS_7 Data without the adjustment:
![image](https://user-images.githubusercontent.com/61746913/82561228-065a9280-9b41-11ea-885c-84599f1512ce.png)
Offset so it aligns with the top of the frame numbers:
![image](https://user-images.githubusercontent.com/61746913/82561762-e8d9f880-9b41-11ea-911e-c9b75100bb52.png)

Let me know if this is okay or if we want some more room?

**Comment by aashish24** [comment]
@BryonLewis it looks right to me (I tried to zoom-in on it). @mattdawkins would need to confirm.
