### ISSUE TITLE
Greying out of non-selected annotations is slightly confusing when finished editing

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#130]
Might be duplicate of a related issue, but if I edit a box, then either right click or left click off of it when finished, all other detections stay grey until I select another object which is a little confusing. Likely for both left clicking on empty space and right clicking it should exit edit mode and everything should be colored again.

**Comment by mattdawkins** [comment]
The grey also blends in completely with some substrate backgrounds so sometimes you can't tell there's another box present to click on to disable the grey. It would be better for the grey out to be disabled as opposed to how it is now.

**Comment by aashish24** [comment]
@mattdawkins so if I understood correctly: 

Grey color -- use if to show editing is disabled
Some other color / or opacity change - use it to show un-selected detections?

**Comment by BryonLewis** [comment]
So I have an inprogress PR that I'm working on that will enable the deselection on clicking blank spaces as well as fix the issue where if you are done editing it will return to color.  So only when you are actively editing it will grey out.  I will switch the grey color to a lighter opacity change.

**Comment by BryonLewis** [comment]
While Editing:
![image](https://user-images.githubusercontent.com/61746913/82579645-1c298100-9b5c-11ea-8c40-22193306839f.png)
While Selected:
![image](https://user-images.githubusercontent.com/61746913/82579713-31061480-9b5c-11ea-892e-b103add92733.png)
