### ISSUE TITLE
Create hotkey for making detection or track annotations

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#151]
Maybe 'c' and 't' respectively?

**Comment by BryonLewis** [comment]
In a previous PR 'n' was added as a new shortcut for new track or new detection.  In an upcoming PR The creation mode settings will be changed and that will allow the user to determine what 'n' does.

**Comment by aashish24** [comment]
@BryonLewis we need to think about adding this to help section
