### ISSUE TITLE
Make seperate make detection and make track options

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#152]
We probably want either:

(1) a separate "+" for either detection (single frame) or tracks (multi-frame) where the track option automatically goes to the next frame, right now it's 

or 

(2) a user-specific setting for switching between these modes

**Comment by mattdawkins** [comment]
The detection creation option after you draw a box you don't want to stay in edit mode, though you do want to keep the target highlighted

**Comment by BryonLewis** [comment]
Simple idea would be two text buttons   (Add Detection)  (Add Track) Add detection will be disabled unless a track is selected.  
Alternatively If a track is selected we can have it say (Edit Detection) which will set it to edit mode immediately when clicked and then when there isn't an existing detection for a track it can say Add Detection.
