### ISSUE TITLE
Increase track box width, they are too low contrast and hard to see; change color scheme

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#153]

**Comment by mattdawkins** [comment]
Low contrast examples:

https://viame.kitware.com/#/viewer/5e95c32895a54f6165d90da7

**Comment by mattdawkins** [comment]
Also:

https://viame.kitware.com/#/viewer/5eb372788d01d968cc165ced

**Comment by BryonLewis** [comment]
![image](https://user-images.githubusercontent.com/61746913/85137914-edaccd80-b20f-11ea-9847-40611c47ba26.png)
I'm hoping the thickness helps fix this at least until we allow users to specify their own colors.
