### ISSUE TITLE
Remove delete confirmation option

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#154]
Too many button clicks

**Comment by mattdawkins** [comment]
Alternatively make it a user-specific setting

**Comment by BryonLewis** [comment]
Can easily be removed, will need to have a bigger discussion with the group about setting up user-specific settings.

**Comment by mattdawkins** [comment]
User-specific settings for this one would definitely make sense

**Comment by mattdawkins** [comment]
In the default case though we don't want it, the standard use case for annotation or annotation correction has users going through thousands of annotations in one sitting; every button press matters
