### ISSUE TITLE
Downloading videos seems to be broken for some folders

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#171]
https://viame.kitware.com/#/folder/5ee3f471e76a2c441ca58e88

tried downloading video only, got empty 22 byte file instead of video

**Comment by mattdawkins** [comment]
if I go up a directory and download everything I get the video, but not at this level

**Comment by BryonLewis** [comment]
Just did some testing on this.  He obviously had a large video which took a while to transcode.  During testing I noticed that if you aren't logged into the system when the transcoding is done it will throw an error.
`Response text: {"message": "You must be logged in.", "type": "access"}`
So it looks like the part of the requirement after finishing the transcoding process is maintaining the user login credentials to be able to `uploadFileToFolder(folderId, output_path)` after it is complete.

I don't have admin access to the viame.kitware.com, but I'm guessing if you review the job logs in girder you will find a similar error there for this specific user.

**Comment by BryonLewis** [comment]
Update:  This same issue occurs for any running pipeline as well:
```
Response text: {"message": "You must be logged in.", "type": "access"}
  File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/girder_worker/task.py", line 160, in __call__
    results = self._maybe_transform_result(0, results)
  File "/usr/local/lib/python3.7/dist-packages/girder_worker/task.py", line 134, in _maybe_transform_result
    return grh.transform(result, **kwargs)
  File "/home/viame_girder/viame_server/transforms.py", line 109, in transform
    self.folder_id, path, **self.upload_kwargs
  File "/usr/local/lib/python3.7/dist-packages/girder_client/__init__.py", line 975, in uploadFileToFolder
    progressCallback)
  File "/usr/local/lib/python3.7/dist-packages/girder_client/__init__.py", line 932, in uploadStreamToFolder
    'file', params, data=_ProgressBytesIO(chunk, reporter=reporter))
  File "/usr/local/lib/python3.7/dist-packages/girder_client/__init__.py", line 495, in post
    data=data, json=json, headers=headers, jsonResp=jsonResp)
  File "/usr/local/lib/python3.7/dist-packages/girder_client/__init__.py", line 481, in sendRestRequest
    response=result)

**Comment by BryonLewis** [comment]
Downloading the video works, this is a separate issue with the playback of the video.

It requires downloading the entire video file before even triggering the `onloadedmetadata` event.  So that means for large 700MB videos it requires loading the entire thing before triggering this value.  It looks like there should be something that allows for http header to get a small content range limit of an area returned instead of the entire element.

**Comment by BryonLewis** [comment]
Update: figure out it was the `/item/download` endpoint was having issues with range requests initiated by the video player.  It was returning 206 responses but the range request functionality wasn't working properly.

**Comment by subdavis** [comment]
Downloaded both videos in the linked directory successfully.  I'm going to consider this closed, feel free to reopen if there's still an issue.
