### ISSUE TITLE
World button on viame.kitware.com doesn't seem to go back to the universal (shared) training data location

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#179]
See images, if I press the 'world' it doesn't go back to the training data page like it use to, this should also probably be in the documentation somewhere what these buttons do and where they go, heard one comment about it being unclear, also how users can upload data and then share the links to the data with other users (public vs private). The only way to get back to the training data page appears to be to go to viame.kitware.com again, no GUI option which is bad

<img width="826" alt="world_no_work" src="https://user-images.githubusercontent.com/2353972/85750534-c8b8ce80-b6d7-11ea-9dc6-b8244d9a5f12.png">

**Comment by mattdawkins** [comment]
Where I think it should go?

<img width="805" alt="carseg" src="https://user-images.githubusercontent.com/2353972/85750775-fef64e00-b6d7-11ea-8229-6ef385afb323.png">

**Comment by subdavis** [comment]
This was fixed in #180
