### ISSUE TITLE
Add switch that controls creating a folder in uploader

### ISSUE THREAD

**Issue by AlmightyYakob** [VIAME/VIAME-Web#19]
Feature that was removed from #18, due to conflict with #17, and missing functionality in the GWC `fileUploader` mixin.

**Comment by subdavis** [comment]
Why would we ever want to not create a folder?  Where would the annotations go if there isn't a folder?

**Comment by AlmightyYakob** [comment]
> Why would we ever want to not create a folder? Where would the annotations go if there isn't a folder?

If you're uploading files without annotations. for the purposing of manually annotating. With the current UI, if you don't upload all of the files you want to annotate in one go, they would be split across several folders.

**Comment by BryonLewis** [comment]
If you are uploading more than one file, we may want to disable the name field.  Overwriting the names could change the file extension types and other information provided for a the list of items.  With a single file we can overwrite the name and extension, but for multiples we probably wouldn't do that.
I'll see if I can provide feedback to the user why we are disabling the field.  (Persistent Hint seems like a good starting point to provide info)
Modify the title of the field to say 'Folder Name' or 'File Name' based on the data in the pending upload.
