### ISSUE TITLE
Update the localStorage settings to have universal and folder specific settings

### ISSUE THREAD

**Issue by BryonLewis** [VIAME/VIAME-Web#204]
Track mode settings are universal, meaning that your defaul type can be saved across different folders/annotation data sets which might not make sense.

We should probably update this to use id of current folder when we are saving folder specific settings like the track/detection modes.

I don't know exactly what we want to do for Universal user settings.  If we want these saved somewhere in girder or just placed in localstorage as well?

**Comment by subdavis** [comment]
It might be worth waiting until a customer has a specific need to address these questions.  Existing functionality might be fine.  Whatever we assume is necessary may be a departure from what's actually useful.

**Comment by BryonLewis** [comment]
I agree, the only thing I notice now is that the default track type when you switch projects could be a type that is unrelated to the data type.  Maybe I just update it so on load it checks existing types and if it isn't an existing type it doesn't default to that.
