### ISSUE TITLE
New type dropdown has low contrast issues on some OS/browser/theme combinations

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#211]
![example_low_contrast](https://user-images.githubusercontent.com/2353972/87163195-fa639500-c294-11ea-8db1-215c27615812.png)

**Comment by mattdawkins** [comment]
I'm on like fedora 21 + dark theme chrome by the way, maybe its using some weird system themes

**Comment by subdavis** [comment]
Yeah, this is a platform problem.  These are browser-native pop-up lists, so the system theme is broken.  We don't have any control over shadow-dom like that....

**Comment by subdavis** [comment]
Disable "use system theme" in chrome to fix this.  Fedora/Chrome bug.
