### ISSUE TITLE
Put edit buttons for each detection entry line to the right of species type text

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#213]
Lots of white space in the detection list, maybe the buttons should be placed to the right of each line not in a new line? Thoughts?

![example_low_contrast](https://user-images.githubusercontent.com/2353972/87163584-9392ab80-c295-11ea-8627-980f39722fc2.png)

**Comment by subdavis** [comment]
This isn't possible.  all track items need to be the same height, and the second row is necessary for track types because they have like 9 buttons instead of 2.

**Comment by mattdawkins** [comment]
Okay, was minor, I'll close the issue?

**Comment by mattdawkins** [comment]
Feel like something should be in that white space, at some point we'll probably want to put the score in the list

**Comment by subdavis** [comment]
Yeah we can put other stuff there
