### ISSUE TITLE
Modify first default box color to not be neon green, maybe others

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#214]
Most look fine, though bright green as the first default seems a bit much to me

(I know we discussed changing these, though I think changing the box width to 2 pixels and making the colors toggleable solved most of the visibility issues and the prior defaults may have been better, with the exception of the 8 colors repeating which needed to be changed)

**Comment by mattdawkins** [comment]
If not reverting to old color schema, 2-4 in this new one also conflict since they're all purple/pink variants

**Comment by BryonLewis** [comment]
I can remove some, the first one isn't always bright green it's just how it decides to take your type name and map it to a color.  The colors are chosen by rotating through a spectrum and picking a color (avoiding Cyan), it then creates a lighter pastel version and a darker version of the same color.  Afterwards the colors are mixed up and a function will map each type name to a color.  Now we could redo it so the mapping is so the colors are always in a order we specify as new items are added.

**Comment by BryonLewis** [comment]
![image](https://user-images.githubusercontent.com/61746913/87340926-c4cdde80-c516-11ea-8ce7-bfcb3c273b2c.png)
These are what I switched it to.  I could change a bit the order of the items by adjusting the randomization function.
