### ISSUE TITLE
Add image identifier to exported detection CSV for image data sets

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME-Web#218]
For data sets where the images don't correspond to frames in a video sequence, provide some additional identifier (probably image name) in the VIAME csv because the frame number alone isn't really enough.

**Comment by subdavis** [comment]
@mattdawkins could you recommend the best way to include this in the VIAME csv format?

**Comment by subdavis** [comment]
For the record, here's how I generated the CSV if anyone else needs one:

```bash
export GIRDER_TOKEN=''
export FOLDER_ID=''
curl -X GET --header 'Accept: application/json' --header "Girder-Token: ${GIRDER_TOKEN}" "https://viame.kitware.com/girder/api/v1/item?folderId=${FOLDER_ID}&limit=2000&sort=lowerName&sortdir=1" | jq -r '[.[]] | to_entries | .[] | [.key, .value.name ] | @csv' | sed s/\"//g
```

**Comment by mattdawkins** [comment]
It's put in column 2 when dealing with the desktop version and images, e.g. see https://github.com/VIAME/VIAME/blob/master/examples/scoring_and_roc_generation/groundtruth.csv; this field can either be a video timestamp or an image filename
