### ISSUE TITLE
Cleanup all dockerhub images

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#219]
I think there's a little ambiguity, e.g. viame-girder-worker where people might not release it's just for the web not the desktop version, maybe viame-web-girder-worker?

**Comment by mattdawkins** [comment]
Also I think https://hub.docker.com/search?q=kitwareviame&type=image (username: kitwareviame) is deprecated and should be removed

**Comment by subdavis** [comment]
This was done.
