### ISSUE TITLE
Possibly make a toolbar at top or bottom of viewer

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#234]
Having button controls for track modifications (interpolation on, splitting tracks, etc... for every track in the list on the left) seems redundant and a waste of important space when there's buttons for every track independently but you can only select one at a given time. What's the point of having them underneath the track for each track? Also the user has to travel further to find them from the main viewer, and having the head/tail points in a different menu is confusing even though that's also track specific. Maybe all these buttons should be in a toolbar at the top of the viewer?

**Comment by subdavis** [comment]
There are several reasons this was done.

* Locality is super important in UX.  The proximity of an entity to the actions you can take on it is a big deal for users.  Clicking the split button within the track they want to split (or delete etc) gives users confidence that the action they're performing does _exactly_ what they think it does and frees them from having to think about "Did I select the right thing?  Let me double-check before I hit this button".
* This style will be very familiar to CVAT users, which is IMO very valuable if we want to have this tool adopted by the community.
 
> seems redundant and a waste of important space

is there something else that would be better to put here?

> Also the user has to travel further to find them from the main viewer

@BryonLewis has some ideas about how to make these available inside the actual viewer.  I don't know how much 

> and having the head/tail points in a different menu is confusing

I completely agree.  That menu predates these new buttons.  We will need to bring the head/tail stuff into the new style.

**Comment by BryonLewis** [comment]
We kind of have this now with the visibility and edit toggles, think this can be closed?

**Comment by subdavis** [comment]
Yeah, I think we can close it.
