### ISSUE TITLE
Add ability to select training conf file when doing model training

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#239]
Training conf files are located in [viame-install]/configs/train_*.conf

**Comment by mattdawkins** [comment]
All runnable training configs are in [install]/configs/train_*.conf

**Comment by AlmightyYakob** [comment]
> All runnable training configs are in [install]/configs/train_*.conf

`[install]/configs/pipelines/train_*.conf`?

**Comment by mattdawkins** [comment]
Yep, missed the pipelines in there.

A bonus feature (though this should be a follow-up issue I think after this one) would be to have some notes which are displayed alongside each pipeline, e.g. this one is for full frame classification, this one is for detection, pixel classification. I could check-in a json somewhere with config file name to descriptions if that would be helpful somewhere in VIAME

**Comment by AlmightyYakob** [comment]
> A bonus feature (though this should be a follow-up issue I think after this one) would be to have some notes which are displayed alongside each pipeline, e.g. this one is for full frame classification, this one is for detection, pixel classification. I could check-in a json somewhere with config file name to descriptions if that would be helpful somewhere in VIAME

Yeah, having that JSON file would be good, either to be directly used or just as documentation.

**Comment by AlmightyYakob** [comment]
Fixed by b733bcf and 0459aac
