### ISSUE TITLE
Update KPF annotation storage

### ISSUE THREAD

**Issue by AlmightyYakob** [VIAME/VIAME-Web#242]
Original comment: https://github.com/VIAME/VIAME-Web/pull/215#discussion_r458330735

The current method is to store up to 3 annotation files as separate items, which is in contrast to how we usually store annotations (1 per item). This would also possibly lead to errors, as if a set of KPF annotations doesn't have all 3 annotation files, but tries to load all 3 when returning the annotations, it could load part of another dataset as annotations.

The other issue is that when trying to return annotations, up to 3 files are loaded, and then converted at call time, to return the annotations converted to Track JSON format. This is _very_ slow. It would be better to run this conversion only once, at upload time. After that, any request for annotations would just return the JSON file that contains them.

**Comment by subdavis** [comment]
resolved in #215 by way of #245
