### ISSUE TITLE
Resolve small types window list when browser is minimized or resolution small (e.g. on a tablet)

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#249]
See attached below, I don't know if there's a way to either allow the user to move the location of the border between the type selectors and track list so you can see more entries, or just a better automatic resize so that you can at least see a 2-3 different types as opposed to just 1 squashed.

<img width="993" alt="example_small_bar" src="https://user-images.githubusercontent.com/2353972/89133080-f539e480-d4e6-11ea-9db1-927e49160b8f.png">

**Comment by BryonLewis** [comment]
I think this can be fixed just by making the minimum size a little greater.  I don't think it matters if there is some blank space if there is only one type:
![image](https://user-images.githubusercontent.com/61746913/92240214-3d537a80-ee8a-11ea-9051-335ab1f41e44.png)

![image](https://user-images.githubusercontent.com/61746913/92240238-47757900-ee8a-11ea-8f8f-c539e6c6285e.png)
