### ISSUE TITLE
Getting polygon annotations into CSV and through pipelines

### ISSUE THREAD

**Issue by BryonLewis** [VIAME/VIAME-Web#253]
Being able to support passing polygon annotations into the pipelines by placing them inside of the CSV.
The input should be similar to the way attributes are added into the CSV.

**Comment by BryonLewis** [comment]
We now have updated VIAME Documentation that specify the format for the Polygon annotations in the CSV.  As of right now they only support a single Polygon.
https://viame.readthedocs.io/en/latest/section_links/detection_file_conversions.html

We also have a new GeoJSON format for polygons and other GeoJSON like data.  I think combined in this issue would be the support for the new Head/Tails GeoJSON data format as well as the Polygon geoJSON format.

**Comment by subdavis** [comment]
@BryonLewis why did #305 not close this?

**Comment by BryonLewis** [comment]
I don't know, but I'm guessing we can close this.  It looks like I removed the link for some reason.
