### ISSUE TITLE
Pressable button locations for seek and edit detection do not align with buttons in certain cases

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#279]
(Doesn't happen on chrome or at the top of track list just very far down in them)

Example reproduction:

Go to:

https://viame.kitware.com/#/viewer/5eb371608d01d968cc1642dd

Scroll to very low in results list this only happens on entries 15000+

Try to click bottom right areas of seek and edit buttons, but they are unclickable you need to move slightly to the top left of the icon

**Comment by subdavis** [comment]
Cannot reproduce on FF 79.0 64 bit for Lubuntu.  Maybe someone else can have a go?

**Comment by mattdawkins** [comment]
Could be specific to my machine I didn't try on a different one

**Comment by mattdawkins** [comment]
I was also on windows FWIW

**Comment by mattdawkins** [comment]
I actually do get this on Linux too, but only if I zoom the bars, e.g. hold control and middle mouse scroll to make the side bars smaller; it only happens when the bars are smaller there

**Comment by BryonCLewis** [comment]
confirmed on FF in windows: 
![image](https://user-images.githubusercontent.com/3180609/90198209-f7315c80-dd9e-11ea-9a61-394889fa8ab8.png)

Update: Looks like it is related to the ID and the digits in it  pushing down the highlight or changing the locked size.
![image](https://user-images.githubusercontent.com/3180609/90198318-58f1c680-dd9f-11ea-945d-def649c27d99.png)
![image](https://user-images.githubusercontent.com/3180609/90198349-6ad36980-dd9f-11ea-9f2b-c33dd89a5f94.png)

Looks like for the `.item-row` the number needs to grow in size and make the input field smaller, specify a locked size or max size of 50/50 for each., or decrease font when numbers get too large.
Dare I ask if we will support 6 figures for the number of tracks?

**Comment by subdavis** [comment]
Please say no.

**Comment by mattdawkins** [comment]
I don't think a limit can be placed on the theoretical number of tracks that can be encountered depending on the length of the sequence and at super low confidence thresholds from processing pipelines there can be many

**Comment by mattdawkins** [comment]
Removed firefox since happens on chrome too after button resize

**Comment by BryonLewis** [comment]
resized the type selection to align with the buttons below it an provide some more room for the trackId:
![image](https://user-images.githubusercontent.com/61746913/92245145-ea7dc100-ee91-11ea-977e-202eccef2516.png)
Then made it so any trackId greater than 7 digits will truncate and provide a hover tooltip to display the real number.
![image](https://user-images.githubusercontent.com/61746913/92245258-1600ab80-ee92-11ea-9e18-e0d8e43923e7.png)
