### ISSUE TITLE
[FEATURE] Create a desktop version of VIAME-Web 

### ISSUE THREAD

**Issue by aashish24** [VIAME/VIAME-Web#293]
**Is your feature request related to a problem? If so, Please describe.**

**Describe the solution you'd like**
A description of what you want to happen.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**

#159

**Comment by subdavis** [comment]
# Remaining tasks

- [ ] Port to windows
- [ ] Implement Training interface
- [ ] Loooots of testing.

**Comment by subdavis** [comment]
Parted out to other issues:

#466
#467
