### ISSUE TITLE
[BUG] Invalid .zip received when downloading from multiple subfolders

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#328]
**To Reproduce**
Steps to reproduce the behaviour:

1. Go to collections benthic training data https://viame.kitware.com/#/folder/5e4c2584a0fc86aa03120c49
2. Download everything for mouss sampler
3. Try to extract downloaded .zip  [error I get is (null) something]

**Comment by mattdawkins** [comment]
Also seems to not work, downloading just detections or everything from:

https://viame.kitware.com/#/folder/5e4c2821a0fc86aa0315c056

Different failure, doesn't even start to download

**Comment by subdavis** [comment]
This is not intended to work and should be disabled.  You can only download a single dataset at a time.
