### ISSUE TITLE
[BUG] When toggling the edit mode outside of track selection, still highlight current selection

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#333]
It's confusing that right now when you select the edit type it doesn't highlight it, but selecting the visibility buttons do toggle them on and off

**Comment by BryonLewis** [comment]
The PR linked will prevent toggling modes outside of editing mode.  That way there isn't this disconnect between clicking and seeing nothing happen.  The only other option is that it is disabled when nothing is selected, but an item is selected it is in an enabled by neutral state and the act of clicking on an editing mode will kick it into that mode?
