### ISSUE TITLE
[FEATURE] Phantom Frames when Exiting Creation mode

### ISSUE THREAD

**Issue by BryonLewis** [VIAME/VIAME-Web#342]
When you click on "+Track" or "+Detection" it creates a track before it is even drawn.  If you hit escape or perform some other action that track will remain but with no geometry or bounds associated with it.  I'm guessing it may have some issues with pipelines and other data with this mode.

This is very prevalent in Detection continuous mode, because it automatically creates a new track for you and the way to exit is to hit escape.

The escape action should trigger a result call to disable the currently selected track.  We may want to check and see if a current track is selected and if it is selected and the `featureIndex` is 0 for it we delete the track instead of just abandoning it.

**Comment by subdavis** [comment]
Removing the phantom detection when escape is pressed seems like an improvement, though.
