### ISSUE TITLE
[FEATURE] implement boolean attributes as checkbox (or switch)

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME-Web#345]
**Is your feature request related to a problem? If so, Please describe.**

2 clicks is too many clicks to set a boolean

**Describe the solution you'd like**

Use a single-click form element like checkbox or switch

**Comment by BryonLewis** [comment]
For this to be done we would need a global 'unset' button for each attribute that places it back into a undefined state.  Boolean attributes technically have 3 states, true/false/unset.  I think it warrants discussion if we should have a checkbox with the ability to unset/remove an attribute from a track/detection.

**Comment by subdavis** [comment]
Close it
