### ISSUE TITLE
[FEATURE] Standardized species list to prevent typos and keep annotations consistent across different videos/users

### ISSUE THREAD

**Issue by aashish24** [VIAME/VIAME-Web#349]
Came out in the NOAA VIAME tutorial from Alex Llich

**Comment by BryonLewis** [comment]
I think this can be closed, now that we have the option to lock types as well as import a list of types that can be used.

**Comment by BryonLewis** [comment]
![typeListDemo](https://user-images.githubusercontent.com/61746913/100254354-316ad800-2f10-11eb-972a-ae50abc4a08c.gif)
Some context for closing this.  You can import list of types as well as lock the types to prevent typos.
