### ISSUE TITLE
[FEATURE] Mass delete for tracks/detections

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME-Web#350]
**Is your feature request related to a problem? If so, Please describe.**
It's too hard to delete everything on a data set.

**Describe the solution you'd like**
Delete all tracks/detections, or delete by type.

**Comment by BryonLewis** [comment]
Don't know if this is what you had in mind, please let me know if you had a different idea for how this would work:
![deletionTool](https://user-images.githubusercontent.com/61746913/95351968-bed66800-088f-11eb-856b-bb1b4ee6142d.gif)
I did this because it is something that may be necessary in the wami annotator for easier filtering of objects.
This is at least a starting point.  GeoJS has what it calls 'brushes' which I believe is a way to select all annotations that intersect with a rectangle that is drawn.  We could use that on a frame to delete multiple annotations at once but will require some more complicated stuff involving highlighting annotations for deletion.

**Comment by subdavis** [comment]
This is one option.   What I had in mind was more like a mass delete on the track list, since the track list allows several dimensions of filtering.

I think there does need to be a select all/none/intermediate checkbox on the type filter list.  This is needed whether you implement mass delete or not, so if you're going to have that, the track list mass delete potentially makes more sense to me.

I'd also put a summary of the pending delete into the dialog to improve user confidence.

```
You are about to delete

2 seriola
14 unknown
5 unknown_fish
```

That way if you want to clear all the tracks, it's 2 clicks, not potentially dozens.

**Comment by BryonLewis** [comment]
I understand what you mean with having a mass delete on all currently visible in the track list and using that as the filter for deletion of items.  I'll add in the capability to delete what is currently displayed in the track and look into the a header check box with the three states (checked, unchecked, box for intermediate). The process of adding a type by editing an existing track has always felt a bit wrong, what do you think about a type creation button above the types?  It creates a disabled type until an item is assigned to it. 

There might be a bigger discussion on what we want to support for the tracklist/typelist filtering and displaying to know where we are ultimately heading.  I know there is another issue about possibly limiting the view in the tracklist to the current frame through a toggle (https://github.com/VIAME/VIAME-Web/issues/286).  Possibly limiting tracks in the track list to the current bounds of the annotator (zoomed in on sea lion annotations, only show those that are visible, could be useful for the event filter and merging in the future).  I know there are performance considerations but it might be also necessary to at some point provide confidence filters on types.  Like now if you run the one pipeline you get  can get back multiple types (vertebrate, invertebrate) and you may want different filters on those types (I know that it complicates exporting and running pipelines with the confidence filter)

**Comment by subdavis** [comment]
> The process of adding a type by editing an existing track has always felt a bit wrong.

I've always found it refreshingly straightforward.  The user doesn't have to worry about creating or deleting types: the type list simply reflects what exists.

Also, a "create type" button would take a 1-click process and turn it into 3-5 clicks.  Sometimes this is necessary in order to lighten the cognitive burden of a task, but I haven't heard any users complaining about that.

We have seen users asking for the ability to define their own pool of types across datasets instead of just entering them in by hand (they view this as a typo risk).   Maybe we should discuss any changes to type creation through that feature request.

**Comment by BryonLewis** [comment]
![UpdatedDelete](https://user-images.githubusercontent.com/61746913/95750102-a50b9b00-0c6a-11eb-826b-36d7fb03e827.gif)
Looking for another round of feedback on this.
This uses your currently visible items to filter for deletion in the typelist or the track list.  So you can use the existing filtering mechanism to delete items.
We can move the type list  deletion into the individual editor tool instead.  How do you feel about the deletion working on the checked items?  It feels a little weird that you un-check items that you don't want to delete.  This just makes me really want to have multi-selection (ctrl+click)  and the ability to delete objects that way.

**Comment by subdavis** [comment]
> This just makes me really want to have multi-selection (ctrl+click) and the ability to delete objects that way.

This would be a different dimension of selection state?  There'd be checkboxes, but those would be unrelated to whatever you'd use to represent multi-select?  That sounds really confusing.

> We can move the type list deletion into the individual editor tool instead

I think it's fine where it is.  I like the "visibility" header.

>  It feels a little weird that you un-check items that you don't want to delete

I agree.  It's not the _most_ straightforward.

Also, how does the confidence filter factor into this?  If there are tracks hidden by confidence, do they get deleted?  If not, I guess there has to be a way to say "delete below confidence"?

-------------------

So far I like everything in the type filter list.  It feels like we've really over-loaded the track list a bit.

However! 

All that being said, this is a low-priorioty issue that I created not really based on any user feedback.  I think this more than meets the level of effort required here.   Incremental change is better.  I'd rather merge something like this and make a second pass on improvements than do the whole thing at once.  If you feel like this is a reasonable candidate to merge, I'd be happy to review it.

IMO, this is done.
