### ISSUE TITLE
[BUG] Edit icons near mouse cursors are distracting and confusing

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#388]
Not sure how you all feel, but I feel that it (a) blocks content behind it (b) just servers as a distraction because there are now 2 things near the cursor. While not critical, my preference would be to remove them unless I'm outvoted here.

Simulatenously the pencil drawing one is confusing because you're not actually drawing anything new just editing.

**Comment by BryonLewis** [comment]
Is this the case to remove all of them?  Or was it only for the "edit" (pencil) icon.  Just for reference the pencil is the standard icon indicating 'edit' when using material design icons.  I do believe that we need some standard way to indicate editing across the application.  We could use text, but obviously an icon is a bit more compact, just like the settings cogwheel.  Either way I can remove all of the mode icons (polygon, bounds, line and edit).

**Comment by subdavis** [comment]
Could we start with just removing the pencil?

I think the "new" indicator (polygon, rect, line) are really useful.
