### ISSUE TITLE
Upload improvements (support folder of folder of images or folder of videos .mpg instead of single video or single folder of images)

### ISSUE THREAD

**Issue by aashish24** [VIAME/VIAME-Web#41]
UPDATE Clarification:  Highest priority we want to be able to create a folder for each high level item in a folder.  Mostly Videos want to be able to uploaded as individual folders instead of a single folder.  Add in a toggle to make it so there are single files.

**Comment by BryonLewis** [comment]
With the updated requirements of having a subfolder and each item in the folder creates it's own sub folder I think the 'Create Folder' checkbox might need to change into a dropdown box instead.

This dropdown will allow the user to specify the upload type.  Provide some tooltip help information for each choice.

- Folder (Create a single folder to upload the files to)
- SubFolders (For each item create a sub folder)
- Current Location (upload all items to the current location)

Changes would be needed for the Subfolders.  I would handle that like multiple pending uploads just not visible to the user.  This would allow us to utilize the existing Upload mixin to upload the files and create the folders.  Doing it this way will allow the existing backend annotation creation and folder setup to remain intact.

**Comment by BryonLewis** [comment]
![image](https://user-images.githubusercontent.com/61746913/79761545-9cf02580-82ef-11ea-9844-1dc5d55cc5ae.png)
Visual style where it will allow the user to determine if the upload location is a Folder, Current, or subfolders.  Subfolder will be disabled if you only are uploading a single item.  The program will suggest the upload location based on the files that are included in the upload.
