### ISSUE TITLE
Preliminary objection detection training - Allow users to train for object detection

### ISSUE THREAD

**Issue by aashish24** [VIAME/VIAME-Web#45]
Currently models are trained via calls to a ‘viame_train_detector’ command line executable tool, e.g.:
https://github.com/VIAME/VIAME/tree/master/examples/object_detector_training
Takes in imagery in a specific format, not sure if we can use this through girder work, directory of directory of images with annotations

**Comment by aashish24** [comment]
@AlmightyYakob we could not cover up this issue in today's meeting but I am wondering if this is something you are going to look into next. I do not remember any road-blockers for this task.

**Comment by AlmightyYakob** [comment]
More things to add that I'm marking down here:

- [ ] Place the training output in a specific folder
- [ ] Expose the pipelines in this folder under a new option (next to detectors and trackers)
- [ ] Add Girder setting to enable/disable training site-wide, which we'll want to set to disabled (per instance, default to allow)
- [ ] Add option to specify output name when running training
- [ ] Add "Run Training" button into viewer as well

**Comment by mattdawkins** [comment]
Also see related https://github.com/VIAME/VIAME-Web/issues/60
