### ISSUE TITLE
[BUG] In output CSVs the highest probability object should be listed first instead of reverse order

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#456]
In output CSVs the highest probability object should be listed first instead of reverse order

**Comment by BryonLewis** [comment]
Just giving a reference #423 where the display of it in the attributes seems to be out of order.  Haven't dug in enough to know if this is client side or if we rely on sorting from the back-end.

**Comment by BryonLewis** [comment]
Double checked it is back-end we just need to sort the array before the CSV_to_tracks conversion to get it in the proper order.  There is more to this on the client side in regards to displaying multi confidence tracks.
