### ISSUE TITLE
Review color choices for the application with UI/UX designe

### ISSUE THREAD

**Issue by aashish24** [VIAME/VIAME-Web#46]

**Comment by BryonLewis** [comment]
This is currently in the Design queue for the UI/UX team.  A document was created with the relevant information in it.

[VIAME-Web UI Document
](https://docs.google.com/document/d/1gOqY9_1PuiIRLri8AGbqp12mv7goLLF5R1clYMV77hI/edit?usp=sharing)[UI/UX Project Dashboard Issue](https://kwgitlab.kitware.com/ux-design/design-tracker/-/issues/39)

**Comment by aashish24** [comment]
@BryonLewis can we setup a meeting with UI/UX team to move this further.

**Comment by BryonLewis** [comment]
Notes:
Had meeting discussing some ideas for UI/UX in VIAME Web, specifically with regards to annotations.

- Default Colors
- UI for user to select colors
- Highlighting while maintaining Type information
- Better highlighting for event view
- Better highlight for timeline view

Faiza will create some mockups and then share them for review.

**Comment by aashish24** [comment]
@BryonLewis thanks for putting a summary of your meeting with Faiza. Looking forward to the recommendations.

**Comment by BryonLewis** [comment]
Faiza has created some mockups that are located on Figma:
[Link to prototype](https://www.figma.com/file/zmtVSmvUMylEsoPyAILq3m/VIAME-(enhancement-of-the-highlight-feature)?node-id=0%3A1)
We can talk about the mockups Tuesday in our meeting.
Below I'll include some images:
![image](https://user-images.githubusercontent.com/61746913/81340822-7fa4b080-907e-11ea-8cfc-898a18376ccf.png)
![image](https://user-images.githubusercontent.com/61746913/81340908-99de8e80-907e-11ea-88d7-0737d7753142.png)
![image](https://user-images.githubusercontent.com/61746913/81341004-d27e6800-907e-11ea-997d-879eb5fb69f2.png)

**Comment by BryonLewis** [comment]
Updated document for references to the Registration screen and included some ideas that Brandon had about how to make the page a bit more friendly with some instructions for the user.  It is posted in the same project for the UI/UX team.
