### ISSUE TITLE
Image filter list not supporting all types of images (SGI)

### ISSUE THREAD

**Issue by BryonLewis** [VIAME/VIAME-Web#48]
The image filter in the uploading of files filters out specific images.
One of the ones to add is SGI
The current list supports:

- .jpg
- .jpeg
- .png
- .bmp

Get from @mattdawkins  a list of images we would like to support

**Comment by mattdawkins** [comment]
.jpg;.jpeg;.JPG;.JPEG;.tif;.tiff;.TIF;.TIFF;.png;.PNG;.sgi;.SGI;.bmp;.BMP;.pgm;.PGM

**Comment by BryonLewis** [comment]
Additional information:
Within the girder data retrieval there is an additional filter for specific types of files.
![image](https://user-images.githubusercontent.com/61746913/79368131-ea017f80-7f1c-11ea-924e-bd3683589d39.png)
This will also need to be updated to support the list

**Comment by BryonLewis** [comment]
We had some discussion about this issue in the slack channel and talked about using Girder's large image format plugin or possibly implementing something else to make it work.  The core is that geoJS is expecting a jpeg or png from the server.  The large image plugin for girder will take tiffs and other formats and serve them up in a large tiled format that geoJS can read.  The only issue with this is the possibly time overheads of doing it in real time, although it can be done ahead of time and cached using memcache.

The other option is to use a version of ffmpeg on the server and during upload we either convert to png/jpgs or we convert into a video from the frames and use that as the source instead.  Either way it looks like we are going to need some backend updates for this to work.

**Comment by AlmightyYakob** [comment]
It seems like `ffmpeg` is mainly used for converting to/from videos, and I can't really find any documentation of it being used to convert videos, or if they support the ones listed. Unless somebody else discovers how to use this properly, and has a compelling reason that we should use `ffmpeg`, I'm going to pursue using [PIL](https://pillow.readthedocs.io/en/stable/) (Python Image Library).

**Comment by BryonLewis** [comment]
My suggestion of ffmpeg is that it could be used to kill 2 birds with one stone.  You now have one tool that can be used to do image conversion and video encoding if needed.  It can convert image sequences into different formats and the documentation says it supports all of the formats listed.
I took the BigBuckBunny test file converted it to SGI files, then using another command took the SGI files and converted them into PNGs. 
[ffpmeg Supported Image Formats](https://www.ffmpeg.org/general.html#Image-Formats)

I think some things like the Benthic dataset with the 5MB images will eventually need to be encoded into video streams to be usable.  On a 100MBps LAN requesting 5MB images you could only get 2.5fps, even at 1GBps you're capped at 25fps playback.

Now because I don't have familiarity with the python stuff or backend it could be completely the wrong tool for the job.  I was just suggesting it based on what I had read.

**Comment by AlmightyYakob** [comment]
Discussed offline with @BryonLewis, it looks like `ffmpeg` actually can do what we want, so I'll be pursuing that route first. If it seems like this approach isn't working out, I can try switching to PIL.
