### ISSUE TITLE
Confirm standard users can't over-write anything in core 'Training Data' folder

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#49]

**Comment by BryonLewis** [comment]
Created a new test account that didn't have admin privileges on the site.
Tried creating new folders, uploading data and tried to delete folders as well.  (Made backups just in case beforehand).
All of the actions failed with proper response messages except for the deletion message.  It errors out in the console without displaying anything to the user.

TODO:  Make it so a deletion without permissions properly warns the user that they don't have the proper permissions to perform the deletion.

Below image can give context into what is needed to be updated:
![image](https://user-images.githubusercontent.com/61746913/88942748-ae36bf80-d258-11ea-8cec-27e799a71142.png)

**Comment by BryonLewis** [comment]
Being addressed in #245
