### ISSUE TITLE
VIAME-Dive JSON file vs folder named .JSON [BUG]

### ISSUE THREAD

**Issue by BryonLewis** [VIAME/VIAME-Web#490]
**Describe the bug**
Notice in I believe both windows and linux if you download everything from server it could include a folder named resuly_{timestampt}.json.  This prevents it from loading properly in VIAME-Dive
**To Reproduce**
1.  Download data from the web version which contains a json file.  Make sure you download everything
2. There should be a folder in there if with the name of `result_{timestamp}.json`
3.  This should prevent the viewer from loading properly.

**Expected behavior**
should properly ignore directories even if they are named with a `.json` inside of them.
**Desktop (please complete the following information):**
 - OS: I believe windows and linux

**Additional context**
I think this should be a simple fix.

**Comment by subdavis** [comment]
I noticed this, then fixed it, then got distracted and stashed the changes last week, and I've lost the stash.

I'll fix it again.

**Comment by BryonLewis** [comment]
I noticed it before (like probably in my initial windows testing) but just deleted the folder and continued my testing and forgot to log/fix the issue.  So I figured I create an issue just to remind myself.
