### ISSUE TITLE
When adding new track go to it in the track list for easier immediate type adjustment

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#50]

**Comment by BryonLewis** [comment]
Looks like the main issue is that when you add a new track it selects it and assigns it an ID before it exists in the tracklist.  It doesn't know to refresh the selected track in the track list once it is created.  Looking into the best way to cause it to update without adding too much complexity.

**Comment by BryonLewis** [comment]
Want to add to this an issue that @AlmightyYakob  found with regards to new tracks.  A new track doesn't create an event in the `eventChartData` array when the type is `undefined` meaning that it can't be gone to using the "Go to First Frame" until it is a type assigned.
I have a small fix that will make 'undefined' a temporary type when a user creates a new item.  This will also help fix the issue of immediately going to the new item for type adjustment.
