### ISSUE TITLE
DIVE importMedia structure[FEATURE]

### ISSUE THREAD

**Issue by BryonLewis** [VIAME/VIAME-Web#517]
@subdavis  - for discussion.
Discussion about the structure of the `importMedia` function currently located in `./backend/native`.

There are slight differences to how ffprobe and ffmpeg are called between the different platform Operating Systems so we need to account for this.

Things that the importMedia function needs to handle based on platform:
- Test video files with ffprobe to determine if they need conversion
- Convert video files if required using ffmpeg
- Convert image files if required

Problem:
Right now the importMedia function is in `common.ts` and the platforms for linux/windows both reference `common.ts` creating  circular dependency if we try to place plaform functions for ffprobe and ffmpeg conversions in there.  So this is mostly an organizational issue.

Options:

- We break out the `importMedia` into a higher level which imports the functions from `common/linux/windows` and utilizes them to perform the import/ffprobe/transcode process and kick off jobs as needed.
- Pass in an object to the `importMedia` call with the relevant functions to call for the ffprobe/transcode processes.
- We make it more like the web version were we have an additional endpoint called `postprocess` which is done after the initial JSON meta creation where it then views the files and modifies them as needed.  It could be done in `Recents.vue` right after `importMedia` is returned. (not my favorite because it requires modification of metaJSON after it is returned once).

**Comment by subdavis** [comment]
> We break out the importMedia into a higher level which imports the functions from common/linux/windows and utilizes them to perform the import/ffprobe/transcode process and kick off jobs as needed.

I would prefer to isolate the platform branching logic so `if (platform === 'windows')` isn't something that can just happen anywhere.  Excluding this to `backend/native/ipcService.ts` would be ideal.  I'd suggest moving importMedia from HTTP to IPC for this reason.

> Pass in an object to the importMedia call with the relevant functions to call for the ffprobe/transcode processes.

For a pseudocode example, I think this works nicely.  

```typescript
ipcMain.handle('import-media', async (_, path: string) => {
  const ret = await common.importMedia(path, {
    ffprobeMethod: currentPlatform.ffprobeMethod,
    ffmpegMethod: currentPlatorm.ffmpegMethod,
  });
  return ret;
});

> We make it more like the web version were we have an additional endpoint called postprocess which is done after the initial JSON meta creation where it then views the files and modifies them as needed.

I'd rather not do this.

**Comment by BryonLewis** [comment]
I don't know why that didn't enter my head as an option.  I wanted to reuse the nice platform stuff we had in ipcService, I just didn't think of moving importMedia into the ipcService.  I like this method as well, thanks.

**Comment by BryonLewis** [comment]
closing, it has been implemented
