### ISSUE TITLE
[BUG] Exiting from continous detection creation mode is confusing

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#541]
I also don't know if it should be the default, if I'm in continuous detection creation mode and a just want to click an existing detection to get out of it I can't

**Comment by BryonLewis** [comment]
You use to be able to either hit escape on the keyboard or a single click anywhere else on the page should get you out of continuous creation mode. 

![image](https://user-images.githubusercontent.com/61746913/105731393-5cb47800-5efd-11eb-9a68-299cb0c83d7a.png)


I see now that the single clicking doesn't work to kick you out of creation mode anymore.  This must of been some other change.  I'll take a look at it to see if I can determine why that is happening now.  If I can't fix the single click to turn it off I'll disable the mode.
