### ISSUE TITLE
[BUG] [UX] Better ux for job creation

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME-Web#551]
This is a ux bug.  People don't realize they've started a job and they create duplicates.

We need a way of indicating that a job is in the queue, as well as a mechanism to prevent or warn about creation of duplicates.

**Comment by subdavis** [comment]
At a minimum, I think there should be some info on the jobs page about what the various symbols mean.

Pause means "in the queue", etc etc.

We should also show the pause icon instead of the spinner if the user has queued jobs.

**Comment by BryonLewis** [comment]
If we're going to muck around in the jobs viewer maybe enable 'user to cancel jobs'

I believe our job spinner on the job Tab inside of the Main view and datset viewer contains a list of datasetIds that are being operated on, we could prompt the user if they want to queue up additional jobs on the current dataset (indicating that there is currently a job in the queue for the current dataset).  I haven't thought or looked how that works with multiple folder training but I imagine the info is still there.

**Comment by subdavis** [comment]
> I think the one of the issues right now is that while we do the  toast message immediately we wait for a notification to start the job spinner on the tab to indicate something is actually happening.  We should assume it's started and then cancel if the job returns back and error.  This data should be used to prompt the user if they attempt to start another pipeline on data that already has one running on it.  I believe all the data should be there to do this already.

- Bryon
