### ISSUE TITLE
[FEATURE] Need way to pass in VIAME installation dir on command line to launcher in Desktop

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#560]
for the .zip installers of VIAME (including DIVE), we already know where VIAME is so the user shouldn't need to set the path, alternatively if there's a way to hard-code it somewhere in source and I can custom build would also work

**Comment by subdavis** [comment]
I reproduced your error from this morning,   I realized that it's just a console dump of the status check on the settings page.

In other words, the error was not an error.  We do need to add a way to set viame path that user doesn't have to manage, though.  I'll do that.
