### ISSUE TITLE
Video Annotations not working properly

### ISSUE THREAD

**Issue by BryonLewis** [VIAME/VIAME-Web#58]
User issue:
"I found your email on your github page for the VIAME. I'm trying to use the web app to upload .mp4 files and then do annotation. I am able to upload the MP4 files successfully, but I never get a 'annotate' blue button next to the files. Is there something I am doing wrong?

The MP4 files are around 2.10GB each. Is there a max file size issue I am running into for using VIAME web app?"

Matthew has noted that no videos have Annotations available for them.

**Comment by BryonLewis** [comment]
i think there are a couple of things going on here that are preventing the Annotation clip from working.

1.  `maybe_mark_folder_for_annotation` this function called when a upload completes looks like it will only mark folders with images inside it for annotation.  I'm guessing we need to modify it so it will mark folders with a list of different types of videos inside it for annotation as well.
2.  The videoURL for the file is retrieved through `viame_detection/clip_meta` endpoint.  That should contain and id for `video:` which will provide a reference to girderRest to file locations being at `/item/{videoId}/files`.  Then finally the first file from that is used to download the file from `api/v1/file/${files[0]._id}/download`.
3.  In both my local version and viame.kitware.com the request to the `viame_detection/clip_meta` returns null for the video.  I need to look into how that is being set and if we are missing a step in the process.

**Comment by AlmightyYakob** [comment]
@BryonLewis Have you already done substantial work on this issue? If so I'll just assign you instead, so that we don't overlap work, it you're alright with that.
