### ISSUE TITLE
Warn user of unsaved edits

### ISSUE THREAD

**Issue by subdavis** [VIAME/VIAME-Web#65]
When a user tries to leave the annotation page, either by closing the tab or going back to the data browser, they should get a modal warning if there are unsaved annotations in the session.

**Comment by BryonLewis** [comment]
Got bit by this before in a demo recording.  I forgot to save before clicking 'Data'.  This is kind of long overdue to have this in there.  This is just a quick implementation of checking before router changes and before browser level changes.  This does use two different styles and I would understand if we wanted to use a singular style for both the browser level actions (reload/closing) and the router level actions:
![saveexitingGuards](https://user-images.githubusercontent.com/61746913/95360999-285b7400-089a-11eb-9f48-524aa1c6d0ca.gif)

I understand that the text may need to change at some point

**Comment by subdavis** [comment]
Looks good to me!  Look forward to a PR.
