### ISSUE TITLE
Add split track option (on current frame)

### ISSUE THREAD

**Issue by mattdawkins** [VIAME/VIAME-Web#67]

**Comment by subdavis** [comment]
More info is needed about the use-case and user:

* What is the flow of the task they're trying to accomplish?
* How does the user identify where a track should be split?
* Do they need to be able to quickly manipulate the two resulting tracks, such as removing frames around the boundary, changing labels, changing attributes, etc?

**Comment by mattdawkins** [comment]
A track was created by an automated tracker but it jumps to the wrong target mid-way through. The GUI then needs to be able to split that track into 2 seperate tracks and then each can be further edited (or a portion deleted if it jumped something else entirely)
